# Netlify Configuration File

[build]
  command = "npm run build"   # Command to build your Vite app
  publish = "dist"            # Folder to deploy (Vite outputs to 'dist')

# Redirect all routes to index.html for client-side routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Set custom headers (for CORS, security, etc.)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'"

# Optional: Add environment variables (can be overridden in Netlify UI)
#[[build.environment]]
#  VITE_API_URL = "https://your-api-url.com"
